# Generated by Django 4.1.3 on 2022-11-15 13:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeruser',
            name='user_dob',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
