# Generated by Django 4.1.3 on 2022-11-21 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_alter_registeruser_user_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeruser',
            name='user_dob',
            field=models.DateField(),
        ),
    ]
