# Generated by Django 4.1.3 on 2022-11-29 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease', models.CharField(max_length=50)),
                ('date', models.DateField(verbose_name='Appointment date')),
                ('timings', models.CharField(choices=[('09:00–10:00', '09:00–10:00'), ('10:00–11:00', '10:00–11:00'), ('11:00–12:00', '11:00–12:00'), ('12:00–01:00', '12:00–01:00'), ('01:00–02:00', '01:00–02:00'), ('02:00–03:00', '02:00–03:00'), ('03:00–04:00', '03:00–04:00'), ('04:00–05:00', '04:00–05:00'), ('05:00–06:00', '05:00–06:00')], default='09:00–10:00', max_length=20, verbose_name='Appointement time')),
                ('description', models.CharField(max_length=50)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.register')),
            ],
        ),
    ]
