# Generated by Django 4.1.3 on 2022-12-03 00:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookappointments',
            name='patients',
            field=models.ForeignKey(db_column='patients', on_delete=django.db.models.deletion.CASCADE, to='patients.register'),
        ),
    ]
