# Generated by Django 4.1.3 on 2022-11-30 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=150)),
                ('user_email', models.EmailField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('user_dob', models.DateField(null=True)),
                ('location', models.CharField(max_length=50)),
                ('user_mobile', models.CharField(max_length=50)),
            ],
        ),
    ]
